// actionTypes.js
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_REGISTER = "AUTH_REGISTER";

export const PROFILE_PIC_UPLOAD_SUCCESS = "PROFILE_PIC_UPLOAD_SUCCESS";
export const PROFILE_PIC_UPLOAD_FAILURE = "PROFILE_PIC_UPLOAD_FAILURE";

export const PROFILE_PIC_REMOVE_SUCCESS = "PROFILE_PIC_REMOVE_SUCCESS";
export const PROFILE_PIC_REMOVE_FAILURE = "PROFILE_PIC_REMOVE_FAILURE";


